version: 2
jobs:
    build:
        docker: 
            -   image: python
                environment:
                    AUDIODEV: null
        working_directory: ~/screenflow-ci
        steps:
            - checkout
            - run:
                name: Application dependencies
                command: pip install -r requirements.txt
            - run:
                name: CI dependencies
                command: pip install pytest pytest-cov coverage codacy-coverage
            - run:
                name: Unit testing
                command: pytest --junitxml=unittests.xml --cov-report term --cov=screenflow
            - run:
                name: Test coverage reporting
                command: coverage xml
            - store_test_results:
                path: unittest.xml
            - store_artifacts:
                path: coverage.xml
                prefix: coverage-report
            - deploy:
                name: Codacy
                command: python-codacy-coverage -r coverage.xml