version: 2
jobs:
    build:
        docker: 
            -   image: python:2.7
                environment:
                    AUDIODEV: null
        working_directory: ~/screenflow-ci
        steps:
            - checkout
            - run:
                name: Install application dependencies
                command: pip install -r requirements.txt
            - run:
                name: Install CI dependencies
                command: pip install pytest pytest-cov coverage codacy-coverage
            - run:
                name: Run unit tests
                command: pytest --junitxml=unittests.xml --cov-report term --cov=screenflow
            - run:
                name: Generate test coverage report
                command: coverage xml
            - store_test_results:
                path: unittest.xml
            - store_artifacts:
                path: coverage.xml
                prefix: coverage-report
            - deploy:
                name: Deploy coverage report to Codacy
                command: python-codacy-coverage -r coverage.xml